### ISSUE TITLE
Rare NullPointerException on Search

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#777]
Occasionally see a `NullPointerException` caused by searching; can't yet reproduce though. Should fix to make sure can't happen ever though!

Stack trace:
```
Caused by: java.lang.NullPointerException
  at uk.ac.cam.cl.dtg.isaac.api.IsaacController.search(IsaacController.java:196)
  at sun.reflect.GeneratedMethodAccessor356.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
  ... 33 more
```

See [`IsaacController.java`](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/isaac/api/IsaacController.java#L196), appears to be an unset `types` parameter.

**Comment by jsharkey13** [comment]
We're still seeing this on the live site, the request that went by was akin to:
`https://staging.isaacphysics.org/api/any/api/search/bolt%20thrower`

We should at least catch the error, if nothing else. It definitely looks to be an unset `types` parameter, but I can't work out how it happens.
